### ISSUE TITLE
Alternates syntax update

### ISSUE THREAD

**Issue by karovski** [eternime/superscript#2]
The syntax for the alternates has been updated to match double parenthesis:
`This is the (( change | update | modification )) in question`

Additionally extra whitespace is trimmed only inside the parenthesis, unlike the trimming of all trailing spaces in the original implementation.

**Comment by silentrob** [comment]
Can you create a PR for this. I would love to merge it back into superscript/master.

**Comment by karovski** [comment]
Ok, created a branch with the cherry picked commits for this issue and sent PR.
