### ISSUE TITLE
Broken conversation flow

### ISSUE THREAD

**Issue by karovski** [eternime/superscript#6]
After merging conversation impl. from upstream (Rob's repo) the main scenarios for eternime stopped working properly.

The issue is pinpointed to this specific commit https://github.com/eternime/superscript/commit/0d1ec757cd6aea887da69474ec725654ff6a8f94

Investigating mocha test on SuperScript showed that the specific case for redirecting to a system topic is not covered, and possibly the redirect tests not being executed at all.

**Comment by silentrob** [comment]
This has been fixed here 2bf55b33919a1069d2e6f62f3cdbca771e91a1b4
